name:                maths
version:             0.1.0.0
github:              "tintinthong/maths"
license:             BSD3
author:              "Justin Thong"
maintainer:          "justinthong93@gmail..com"
copyright:           "2018 Justin Thong"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Package containing repertoire of mathematical functions
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/tintinthong/maths#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  maths-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - maths

tests:
  maths-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - maths
